//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcKayitProgram.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BilgisayarTABLO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BilgisayarTABLO()
        {
            this.ProgramBilgisayar = new HashSet<ProgramBilgisayar>();
        }
    
        public int BilgisayarID { get; set; }
        public string BilgisayarAdi { get; set; }
        public string BilgisayarModeli { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<System.DateTime> KurulumTarihi { get; set; }
    
        public virtual PersonelTablosu PersonelTablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramBilgisayar> ProgramBilgisayar { get; set; }
    }
}
