//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcKayitProgram.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbPcKayitEntities3 : DbContext
    {
        public dbPcKayitEntities3()
            : base("name=dbPcKayitEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DepartmanTablo> DepartmanTablo { get; set; }
        public virtual DbSet<PersonelTablosu> PersonelTablosu { get; set; }
        public virtual DbSet<SirketTablo> SirketTablo { get; set; }
        public virtual DbSet<UnvanTablo> UnvanTablo { get; set; }
        public virtual DbSet<BilgisayarTABLO> BilgisayarTABLO { get; set; }
        public virtual DbSet<ProgramTABLO> ProgramTABLO { get; set; }
        public virtual DbSet<ProgramBilgisayar> ProgramBilgisayar { get; set; }
        public virtual DbSet<KullaniciTablo> KullaniciTablo { get; set; }
    }
}
