//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcKayitProgram.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelTablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonelTablosu()
        {
            this.BilgisayarTABLO = new HashSet<BilgisayarTABLO>();
        }
    
        public int PersonelID { get; set; }
        public string PersonelAdi { get; set; }
        public Nullable<int> UnvanID { get; set; }
        public Nullable<int> SirketID { get; set; }
        public Nullable<int> DepartmanID { get; set; }
        public string PersonelTel { get; set; }
        public string PersonelMail { get; set; }
    
        public virtual DepartmanTablo DepartmanTablo { get; set; }
        public virtual SirketTablo SirketTablo { get; set; }
        public virtual UnvanTablo UnvanTablo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BilgisayarTABLO> BilgisayarTABLO { get; set; }
    }
}
