//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcKayitProgram.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramBilgisayar
    {
        public int ComputerProgramID { get; set; }
        public Nullable<int> BilgisayarID { get; set; }
        public Nullable<int> ProgramID { get; set; }
    
        public virtual BilgisayarTABLO BilgisayarTABLO { get; set; }
        public virtual ProgramTABLO ProgramTABLO { get; set; }
    }
}
