//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcKayitProgram.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnvanTablo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnvanTablo()
        {
            this.PersonelTablosu = new HashSet<PersonelTablosu>();
        }
    
        public int UnvanID { get; set; }
        public string UnvanAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelTablosu> PersonelTablosu { get; set; }
    }
}
